---

- hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ standard_admin_user }}"
  roles:
    - role: hendrikhuels.cd.manage_hosts
    - role: hendrikhuels.cd.manage_sysctl
    - role: hendrikhuels.cd.manage_tools