---

- hosts: all
  gather_facts: false
  become: true
  roles:
    - role: hendrikhuels.cd.manage_hosts
    - role: hendrikhuels.cd.manage_sysctl
    - role: hendrikhuels.cd.manage_tools
    - role: hendrikhuels.cd.sshd
